
set(CMAKE_SYSTEM_NAME       Windows)
set(CMAKE_SYSTEM_PROCESSOR  ${CMAKE_HOST_SYSTEM_PROCESSOR})
set(CMAKE_SYSROOT)

set(CMAKE_C_COMPILER        "x86_64-w64-mingw32-gcc")
set(CMAKE_CXX_COMPILER      "x86_64-w64-mingw32-g++")
set(CMAKE_RC_COMPILER       "x86_64-w64-mingw32-windres")
set(CMAKE_RANLIB_COMPILER   "x86_64-w64-mingw32-ranlib")

set(CMAKE_FIND_ROOT_PATH    "${TOOLCHAIN_PREFIX}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
